+rlimits
eqimd/minisandbox pull request #5
Opened 2022-05-16 17:21 UTC by bagrorg

2022-05-17 09:25 UTC, eqimd requested changes

2022-05-17 09:25 UTC, eqimd commented on src/sandbox/sandbox.cpp
> +        if (WIFSTOPPED(statloc) && WSTOPSIG(statloc) & (1u << 7)) {
`1u << 7` надо вынести в константу

2022-05-17 09:25 UTC, eqimd commented on src/sandbox/sandbox.cpp
> +            if (WSTOPSIG(statloc) == 11) {
11 это SIGSEGV, он явно где-то уже должен быть как константа

2022-05-17 09:25 UTC, eqimd commented on src/sandbox/sandbox.cpp
> +            continue;
этот `if` я бы переписал как
```
if (...) {
} else if ( ... == 11) {
    throw ...
} else {
    conitnue;
}

2022-05-17 09:25 UTC, eqimd commented on src/sandbox/sandbox.cpp
> +            if (WIFSTOPPED(statloc) && WSTOPSIG(statloc) & (1u << 7)) {
`1u << 7` в константу

2022-05-19 13:35 UTC, Nekrolm commented on src/sandbox/sandbox.cpp
> +        if (WIFSTOPPED(statloc) && WSTOPSIG(statloc) & (1u << 7)) {
Лучше всю проверку в отдельную функцию. Потому что не понятно, какое дать специальной магической константе

2022-05-19 13:38 UTC, Nekrolm commented on src/sandbox/sandbox.cpp
>      drop_privileges();
чтобы не трассировать системные вызовы внутри libcap и прочих, лучше дропнуть привелегии до подключения отладчика

2022-05-21 07:32 UTC, eqimd approved these changes

2022-05-21 07:32 UTC, merged