Empowerment
eqimd/minisandbox pull request #7
Opened 2022-05-18 00:09 UTC by pogrebnoijak

2022-05-18 08:58 UTC, pogrebnoijak commented
Чтобы это работало надо ещё предварительно выставить _capabilities_ для исполняемого файла - _setcap CAP_SETFCAP+ep <...>_

2022-05-19 10:07 UTC, eqimd requested changes

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +    std::cout << "empower " << ruid << " " << euid << " " << suid << "\n";  //
Ты прописал `using`-и, но тут написал через `std::`, мне кажется лучше убрать юзинги и всё через `std::` писать

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +        perror("set_uid: getresuid failed");
Обычно мы кидаем исключения

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +    std::cout << "empower " << ruid << " " << euid << " " << suid << "\n";  //
и в принципе эта строка видимо с дебага осталась

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +        perror("set_uid: setresuid failed");
Обычно мы кидаем исключения

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +            perror("show_capabilities.cap_get_file");
Обычно мы кидаем исключения

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +            cout << "caps: " << endl;
видимо осталось с дебага

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +            perror("show_capabilities.cap_to_text");
Обычно мы кидаем исключения

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +                perror("cap_free");
Обычно мы кидаем исключения

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +            cout << "caps: " << txt_caps << endl;
видимо осталось с дебага

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +        perror("cap_free");
Обычно мы кидаем исключения

2022-05-19 10:07 UTC, eqimd commented on src/empowerment/empowerment.cpp
> +            cerr << "Failed to set capabilities of file " << filename << ": " << strerror(errno) << endl;
Обычно мы кидаем исключения

2022-05-19 10:07 UTC, eqimd commented on src/sandbox/sandbox.cpp
> +    minisandbox::empowerment::set_uid();
В старой версии была проблема, что при запуске через `sudo` права всё таки не сбрасывались, сейчас там другой код. Работает ли твоё решение с `sudo`?

2022-05-19 10:12 UTC, eqimd commented on src/sandbox/sandbox.cpp
> +    minisandbox::empowerment::set_uid();
и ещё привилегии надо дропать после сисколла `pivot_root` и после `umount`-а старого рута, иначе будет жаловаться, что прав не хватает

2022-05-19 12:05 UTC, pogrebnoijak commented on src/sandbox/sandbox.cpp
> +    minisandbox::empowerment::set_uid();
Нет, нам надо сбрасывать suid бит, но это невозможно если у нас ruid и так равен ему. Возможно стоит заранее выдать какие-то разрешения, которые нужны для этого. Например мне, чтобы я мог менять _capabilities_ у других файлов надо _setcap_ вызывать - тут думаю надо в ней флагов докидать просто

2022-05-19 13:41 UTC, merged